AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS - Node Group

Resources:
  EKSNodegroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      AmiType: AL2_x86_64
      ClusterName: !ImportValue ClusterName
      DiskSize: 20
      InstanceTypes:
        - t3.medium
      Labels:
        Name: cdnCapstoneNodeGroup
        Scope: UdacityCloudDevopsEngineerNanodegree
      NodeRole: !ImportValue eksNodeInstanceRole
      RemoteAccess:
        Ec2SshKey: cdnCapstone
      ScalingConfig:
        MinSize: 2
        DesiredSize: 2
        MaxSize: 4
      Subnets:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2
      Tags:
        Key: Scope
        Value: UdacityCloudDevopsEngineerNanodegree
